### ISSUE TITLE
Hide options

### ISSUE THREAD

**Issue by ZBLEX** [pitininja/select-mania#10]
Bonjour à toi Pitininja,

Je pense que la possibilité de hide/show des options dans le select serait vraiment pratique et rendrait enfin select-mania l'un des plugin les plus incontournable du web 2.0.

Très amicalement,
ZBLEX

_English translation:
It would be great if I could hide options in the select._

**Comment by pitininja** [comment]
That would be a great feature, will be implemented soon.

It will probably be a `data-hidden` attribute to set on the options in order to hide them.

**Comment by pitininja** [comment]
Mon cher Louis, ton souhait est exhaussé: l'attribut `data-hidden="true"` te permet désormais de cacher des options ou groupes d'options. Disponible dans la dernière release (v1.6). Check la documentation pour plus de détails. Enjoy :)

_English translation:
A `data-hidden="true"` can now be placed on option and optgroup elements in order to hide them. This feature is available in the v1.6 release._

**Comment by ZBLEX** [comment]
Merci beaucoup pour ce développement des plus rapides.

_English translation:
Thanks for this fast development_
